---
- name: Install Apache
  yum: name=httpd state=present enablerepo=remi,remi-php72

- name: Start Apache
  service: name=httpd state=started enabled=yes

- name: Enable .htaccess
  replace:
    dest=/etc/httpd/conf/httpd.conf
    regexp='AllowOverride None'
    replace='AllowOverride All'