---
- name: Install php
  yum : name={{ item }} state=present enablerepo=remi,epel
  with_items :
    - php
    - php-common
    - php-cli
    - php-curl
    - php-gd
    - php-mcrypt
    - php-mbstring
    - php-mysqlnd
    - php-opcache
    - php-pear
    - php-pdo
    - php-xml

- name: Configure php.ini
  template: src=php.ini.tpl dest=/etc/php.ini
